const KEY='prime-hospital-opd-v2';
const CONFIG={url:'https://xcvjyohvrfakhxoevlff.supabase.co',anonKey:'sb_publishable_m7rsHfm0OpEtSrQui8HAiA_59l_S3UV'};
let db;
const state={view:'home',patient:null,visit:null};
window.data={patients:[],visits:[],medicines:[],templates:[]};
const $=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10),uid=()=>crypto.randomUUID();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){localStorage.setItem(KEY,JSON.stringify(window.data))}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');Object.assign(window.data,{patients:x.patients||[],visits:x.visits||[],medicines:x.medicines||[],templates:x.templates||[]})}catch{}}
function nextUHID(){let n=window.data.patients.reduce((m,p)=>Math.max(m,parseInt(String(p.uhid||'').replace(/\D/g,''))||0),0);return 'PH-'+String(n+1).padStart(6,'0')}
function init(){db=window.supabase.createClient(CONFIG.url,CONFIG.anonKey)}
async function boot(){load();init();const {data:{session}}=await db.auth.getSession();if(session){await syncFromCloud();showApp()}else loginScreen()}
function loginScreen(error=''){document.body.innerHTML='<div id="app"></div>';$('#app').innerHTML=`<div class="login"><div class="login-card"><div class="brand"><div class="brand-mark">PH</div><h1>PRIME HOSPITAL</h1><div class="muted">OPD MANAGEMENT SYSTEM</div></div>${error?`<div class="error">${esc(error)}</div>`:''}<div class="field"><label>EMAIL</label><input id="email" type="email" autocomplete="username"></div><div class="field"><label>PASSWORD</label><input id="password" type="password" autocomplete="current-password"></div><button id="login" class="btn primary wide">LOGIN</button><p class="muted login-note">SECURE DOCTOR LOGIN</p></div></div>`;$('#login').onclick=login;$('#password').onkeydown=e=>{if(e.key==='Enter')login()}}
async function login(){const email=$('#email').value.trim(),password=$('#password').value;if(!email||!password){loginScreen('ENTER EMAIL AND PASSWORD.');return}const b=$('#login');b.disabled=true;b.textContent='SIGNING IN…';const {error}=await db.auth.signInWithPassword({email,password});if(error){loginScreen('LOGIN FAILED: '+error.message);return}await syncFromCloud();showApp()}
async function logout(){await db.auth.signOut();loginScreen()}
function showApp(){state.view='home';renderApp()}
function renderApp(){document.body.innerHTML='<div id="app"></div>';$('#app').innerHTML=`<div class="app-shell"><header class="topbar"><div class="top-brand">PRIME HOSPITAL • OPD</div><div class="top-actions"><span class="pill" id="net">${navigator.onLine?'ONLINE':'OFFLINE'}</span><span class="pill" id="sync">${window.data.visits.some(v=>v.syncStatus!=='synced')?'PENDING SYNC':'SYNCED'}</span><button id="logout" class="btn secondary">LOGOUT</button></div></header><div class="layout"><aside class="sidebar"><nav class="nav">${[['home','⌂ HOME'],['consult','＋ NEW CONSULTATION'],['patients','▣ PATIENTS & HISTORY'],['dashboard','▥ DASHBOARD'],['medicines','▤ MEDICINE LIBRARY'],['templates','▧ TREATMENT TEMPLATES'],['shortcuts','★ CLINICAL SHORTCUTS']].map(x=>`<button class="${state.view===x[0]?'active':''}" data-view="${x[0]}">${x[1]}</button>`).join('')}</nav></aside><main id="main" class="main"></main></div></div>`;$('#logout').onclick=logout;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;renderApp()});renderView()}
function renderView(){const m=$('#main');({home,consult,patients,dashboard,medicines,templates,shortcuts}[state.view])(m)}
function go(v){state.view=v;renderApp()}
function home(m){m.innerHTML=`<div class="page-title"><h2>HOME</h2><span class="muted">${today()}</span></div><div class="grid cards"><div class="card"><div class="muted">TODAY'S VISITS</div><div class="stat">${window.data.visits.filter(v=>v.date===today()).length}</div></div><div class="card"><div class="muted">PATIENTS</div><div class="stat">${window.data.patients.length}</div></div><div class="card"><div class="muted">MEDICINES</div><div class="stat">${window.data.medicines.length}</div></div><div class="card"><div class="muted">PENDING SYNC</div><div class="stat">${window.data.visits.filter(v=>v.syncStatus!=='synced').length}</div></div></div><div class="section"><h3>QUICK ACTIONS</h3><div class="toolbar"><button class="btn primary" onclick="go('consult')">NEW CONSULTATION</button><button class="btn secondary" onclick="go('patients')">PATIENTS & HISTORY</button><button class="btn secondary" onclick="go('medicines')">MEDICINE LIBRARY</button></div><div class="muted">LOCAL-FIRST STORAGE • CLOUD SYNC WHEN ONLINE</div></div>`}
function consult(m){const p=state.patient||{},v=state.visit||{},ms=v.medicines||[];m.innerHTML=`<div class="page-title"><h2>${state.visit?'OPEN VISIT':'NEW CONSULTATION'}</h2><span class="muted">DATE: <b>${v.date||today()}</b></span></div><form id="cf"><div class="section"><h3>PATIENT DETAILS</h3><div class="form-grid">${field('firstName','FIRST NAME *',p.firstName||v.firstName,'required')}<div class="field"><label>UHID</label><input name="uhid" readonly value="${esc(p.uhid||v.uhid||nextUHID())}"></div>${field('age','AGE',p.age||v.age,'type="number" min="0"')}<div class="field"><label>SEX</label><select name="sex"><option value="">SELECT</option>${['MALE','FEMALE','OTHER'].map(x=>`<option ${x===(p.sex||v.sex)?'selected':''}>${x}</option>`).join('')}</select></div>${field('mobile','MOBILE',p.mobile||v.mobile,'inputmode="tel"')}${field('weight','WEIGHT (KG)',v.weight)}${field('bp','BP',v.bp,'placeholder="120/80"')}${field('pulse','PULSE',v.pulse)}${field('spo2','SPO2',v.spo2)}${field('temp','TEMP',v.temp)}</div></div><div class="section"><h3>CLINICAL DETAILS</h3><div class="form-grid"><div class="field span2"><label>COMPLAINTS</label><textarea name="complaints" rows="2">${esc(v.complaints)}</textarea></div><div class="field span2"><label>KNOWN CASE OF / HABITS</label><input name="knownCase" value="${esc(v.knownCase)}"></div>${area('history','HISTORY',v.history)}${area('examination','EXAMINATION',v.examination)}${area('pd','PD (PROVISIONAL DIAGNOSIS)',v.pd,'span2')}${area('investigation','INVESTIGATION',v.investigation,'span2')}${area('advice','ADVICE',v.advice,'span2')}${area('management','MANAGEMENT',v.management,'span2')}</div></div><div class="section"><h3>PRESCRIPTION / MEDICINES</h3><div id="medRows">${ms.length?ms.map(medRow).join(''):medRow({})}</div><button type="button" class="btn secondary" onclick="addMed()">＋ ADD MEDICINE</button></div><div class="section consult-actions"><button type="button" class="btn secondary" onclick="go('home')">CANCEL</button><button type="button" class="btn secondary" onclick="saveVisit(true)">SAVE & PRINT</button><button class="btn primary">SAVE VISIT</button></div></form>`;$('#cf').onsubmit=e=>{e.preventDefault();saveVisit(false)};tabs()}
function field(n,l,v='',extra=''){return `<div class="field"><label>${l}</label><input name="${n}" value="${esc(v)}" ${extra}></div>`}
function area(n,l,v='',cl='span4'){return `<div class="field ${cl}"><label>${l}</label><textarea name="${n}" rows="2">${esc(v)}</textarea></div>`}
function medRow(x={}){return `<div class="medicine-row" data-med-row><input data-med="name" list="medicineList" placeholder="MEDICINE" value="${esc(x.name)}"><input data-med="dose" placeholder="DOSE" value="${esc(x.dose)}"><input data-med="frequency" placeholder="FREQUENCY" value="${esc(x.frequency)}"><input data-med="duration" placeholder="DURATION" value="${esc(x.duration)}"><button type="button" class="btn danger" onclick="this.parentElement.remove()">×</button></div>`}
function addMed(){document.querySelector('#medRows').insertAdjacentHTML('beforeend',medRow());tabs()}
function tabs(){const a=[...document.querySelectorAll('#cf input,#cf select,#cf textarea')];a.forEach((x,i)=>x.onkeydown=e=>{if(e.key==='Enter'&&x.tagName!=='TEXTAREA'){e.preventDefault();a[i+1]?.focus()}});if(!$('medicineList'))document.body.insertAdjacentHTML('beforeend',`<datalist id="medicineList">${window.data.medicines.map(x=>`<option value="${esc(x.name)}">`).join('')}</datalist>`)}
function meds(){return [...document.querySelectorAll('[data-med-row]')].map(r=>Object.fromEntries([...r.querySelectorAll('[data-med]')].map(i=>[i.dataset.med,i.value.trim()]))).filter(x=>x.name)}
async function saveVisit(print=false){const f=new FormData($('#cf')),first=f.get('firstName')?.trim();if(!first)return alert('FIRST NAME IS REQUIRED.');const p={id:state.patient?.id||uid(),uhid:f.get('uhid'),firstName:first,age:f.get('age'),sex:f.get('sex'),mobile:f.get('mobile'),createdAt:state.patient?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),syncStatus:'pending'};const pi=window.data.patients.findIndex(x=>x.id===p.id||x.uhid===p.uhid);if(pi>=0){p.id=window.data.patients[pi].id;window.data.patients[pi]={...window.data.patients[pi],...p}}else window.data.patients.push(p);const v={id:state.visit?.id||uid(),patientId:p.id,date:state.visit?.date||today(),...Object.fromEntries(f.entries()),medicines:meds(),syncStatus:'pending',updatedAt:new Date().toISOString()};const vi=window.data.visits.findIndex(x=>x.id===v.id);if(vi>=0)window.data.visits[vi]=v;else window.data.visits.push(v);persist();if(navigator.onLine)await syncToCloud();if(print)printVisit(v,p);else{state.patient=null;state.visit=null;go('patients')}}
function patients(m){m.innerHTML=`<div class="page-title"><h2>PATIENTS & HISTORY</h2><button class="btn primary" onclick="go('consult')">＋ NEW CONSULTATION</button></div><div class="section"><div class="toolbar"><input id="ps" placeholder="SEARCH NAME / UHID / MOBILE"><button class="btn secondary" onclick="$('#ps').value='';patientTable()">CLEAR</button></div><div id="pt"></div></div>`;$('#ps').oninput=patientTable;patientTable()}
function patientTable(){const q=($('#ps')?.value||'').toLowerCase(),ps=window.data.patients.filter(p=>[p.firstName,p.uhid,p.mobile].join(' ').toLowerCase().includes(q));$('#pt').innerHTML=ps.length?`<div class="table-wrap"><table class="table"><thead><tr><th>UHID</th><th>NAME</th><th>AGE/SEX</th><th>MOBILE</th><th>VISITS</th><th>ACTION</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${esc(p.uhid)}</td><td>${esc(p.firstName)}</td><td>${esc(p.age)} / ${esc(p.sex)}</td><td>${esc(p.mobile)}</td><td>${window.data.visits.filter(v=>v.patientId===p.id).length}</td><td><button class="btn secondary" onclick="openPatient('${p.id}')">OPEN HISTORY</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">NO PATIENTS FOUND.</div>'}
function openPatient(id){const p=window.data.patients.find(x=>x.id===id),vs=window.data.visits.filter(v=>v.patientId===id).sort((a,b)=>b.date.localeCompare(a.date));$('#main').innerHTML=`<div class="page-title"><div><h2>${esc(p.firstName)}</h2><div class="muted">${esc(p.uhid)} • ${esc(p.age)} / ${esc(p.sex)} • ${esc(p.mobile)}</div></div><button class="btn primary" onclick="newVisit('${p.id}')">NEW VISIT</button></div><div class="section"><h3>VISIT HISTORY</h3>${vs.length?`<div class="table-wrap"><table class="table"><thead><tr><th>DATE</th><th>COMPLAINTS</th><th>DIAGNOSIS</th><th>MEDICINES</th><th>ACTION</th></tr></thead><tbody>${vs.map(v=>`<tr><td>${esc(v.date)}</td><td>${esc(v.complaints)}</td><td>${esc(v.pd)}</td><td>${esc((v.medicines||[]).map(x=>x.name).join(', '))}</td><td><button class="btn secondary" onclick="openVisit('${v.id}')">OPEN / PRINT</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">NO VISITS.</div>'}</div>`}
function newVisit(id){state.patient=window.data.patients.find(p=>p.id===id);state.visit=null;go('consult')}
function openVisit(id){state.visit=window.data.visits.find(v=>v.id===id);state.patient=window.data.patients.find(p=>p.id===state.visit.patientId);go('consult')}
function dashboard(m){const vs=window.data.visits.slice().sort((a,b)=>b.date.localeCompare(a.date));m.innerHTML=`<div class="page-title"><h2>DASHBOARD</h2></div><div class="grid cards"><div class="card"><div class="muted">TOTAL VISITS</div><div class="stat">${vs.length}</div></div><div class="card"><div class="muted">TOTAL PATIENTS</div><div class="stat">${window.data.patients.length}</div></div><div class="card"><div class="muted">SYNCED</div><div class="stat">${vs.filter(v=>v.syncStatus==='synced').length}</div></div><div class="card"><div class="muted">PENDING</div><div class="stat">${vs.filter(v=>v.syncStatus!=='synced').length}</div></div></div><div class="section"><h3>RECENT VISITS</h3><div class="table-wrap"><table class="table"><thead><tr><th>DATE</th><th>UHID</th><th>NAME</th><th>DIAGNOSIS</th></tr></thead><tbody>${vs.slice(0,20).map(v=>`<tr><td>${esc(v.date)}</td><td>${esc(v.uhid)}</td><td>${esc(v.firstName)}</td><td>${esc(v.pd)}</td></tr>`).join('')}</tbody></table></div></div>`}
function medicines(m){m.innerHTML=`<div class="page-title"><h2>MEDICINE LIBRARY</h2></div><div class="section"><div class="toolbar"><input id="mn" placeholder="MEDICINE NAME"><button class="btn primary" onclick="addMedicine()">＋ ADD MEDICINE</button></div><div class="table-wrap"><table class="table"><thead><tr><th>MEDICINE</th><th>ACTION</th></tr></thead><tbody>${window.data.medicines.map(x=>`<tr><td>${esc(x.name)}</td><td><button class="btn danger" onclick="deleteMedicine('${x.id}')">DELETE</button></td></tr>`).join('')}</tbody></table></div></div>`}
async function addMedicine(){const name=$('#mn').value.trim();if(!name)return;window.data.medicines.push({id:uid(),name,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),syncStatus:'pending'});persist();await syncToCloud();go('medicines')}
async function deleteMedicine(id){if(!confirm('DELETE THIS MEDICINE?'))return;window.data.medicines=window.data.medicines.filter(x=>x.id!==id);persist();if(navigator.onLine)await db.from('medicines').delete().eq('id',id);go('medicines')}
function templates(m){m.innerHTML=`<div class="page-title"><h2>TREATMENT TEMPLATES</h2></div><div class="section"><div class="toolbar"><input id="tn" placeholder="TEMPLATE NAME"><input id="td" placeholder="TEMPLATE TEXT"><button class="btn primary" onclick="addTemplate()">＋ SAVE TEMPLATE</button></div>${window.data.templates.map(x=>`<div class="template-row"><b>${esc(x.name)}</b><span>${esc(x.data?.text||'')}</span><button class="btn danger" onclick="deleteTemplate('${x.id}')">DELETE</button></div>`).join('')||'<div class="empty">NO TEMPLATES.</div>'}</div>`}
async function addTemplate(){const name=$('#tn').value.trim();if(!name)return;window.data.templates.push({id:uid(),name,data:{text:$('#td').value.trim()},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),syncStatus:'pending'});persist();await syncToCloud();go('templates')}
async function deleteTemplate(id){if(!confirm('DELETE THIS TEMPLATE?'))return;window.data.templates=window.data.templates.filter(x=>x.id!==id);persist();if(navigator.onLine)await db.from('templates').delete().eq('id',id);go('templates')}
function shortcuts(m){m.innerHTML=`<div class="page-title"><h2>CLINICAL SHORTCUTS</h2></div><div class="section"><h3>QUICK ENTRY</h3><div class="shortcut-grid">${['FEVER','URTI','GASTRITIS','DIARRHOEA','HEADACHE','BODY ACHE','ALLERGIC RHINITIS','DERMATITIS','DIABETES FOLLOW-UP','HYPERTENSION FOLLOW-UP'].map(x=>`<button class="btn secondary" onclick="shortcut('${x}')">${x}</button>`).join('')}</div></div>`}
function shortcut(x){go('consult');setTimeout(()=>{const c=$('[name="complaints"]');if(c)c.value=c.value?c.value+'; '+x:x},50)}
async function syncFromCloud(){if(!navigator.onLine)return;setSync('SYNCING…');const [p,v,m,t]=await Promise.all([db.from('patients').select('*'),db.from('visits').select('*'),db.from('medicines').select('*'),db.from('templates').select('*')]);if(p.error||v.error||m.error||t.error){setSync('SYNC ERROR');return}window.data.patients=(p.data||[]).map(x=>({id:x.id,uhid:x.uhid,firstName:x.first_name,age:x.age,sex:x.sex,mobile:x.mobile,createdAt:x.created_at,updatedAt:x.updated_at,syncStatus:'synced'}));window.data.visits=(v.data||[]).map(x=>({...x,...x.clinical,date:x.visit_date,syncStatus:'synced'}));window.data.medicines=(m.data||[]).map(x=>({...x,syncStatus:'synced'}));window.data.templates=(t.data||[]).map(x=>({...x,syncStatus:'synced'}));persist();setSync('SYNCED')}
function setSync(x){if($('#sync'))$('#sync').textContent=x}
async function syncToCloud(){if(!navigator.onLine)return;setSync('SYNCING…');try{const {data:{user}}=await db.auth.getUser();if(!user)throw Error('NOT AUTHENTICATED');for(const p of window.data.patients){const {error}=await db.from('patients').upsert({id:p.id,user_id:user.id,uhid:p.uhid,first_name:p.firstName,age:p.age,sex:p.sex,mobile:p.mobile,created_at:p.createdAt||new Date().toISOString(),updated_at:p.updatedAt||new Date().toISOString()});if(error)throw error;p.syncStatus='synced'}for(const v of window.data.visits){const clinical={firstName:v.firstName,uhid:v.uhid,age:v.age,sex:v.sex,mobile:v.mobile,weight:v.weight,bp:v.bp,pulse:v.pulse,spo2:v.spo2,temp:v.temp,complaints:v.complaints,knownCase:v.knownCase,history:v.history,examination:v.examination,pd:v.pd,investigation:v.investigation,advice:v.advice,management:v.management};const {error}=await db.from('visits').upsert({id:v.id,user_id:user.id,patient_id:v.patientId,visit_date:v.date,clinical,medicines:v.medicines||[],updated_at:v.updatedAt||new Date().toISOString()});if(error)throw error;v.syncStatus='synced'}for(const x of window.data.medicines){const {error}=await db.from('medicines').upsert({id:x.id,user_id:user.id,name:x.name,data:{},updated_at:x.updatedAt||new Date().toISOString()});if(error)throw error;x.syncStatus='synced'}for(const x of window.data.templates){const {error}=await db.from('templates').upsert({id:x.id,user_id:user.id,name:x.name,data:x.data||{},updated_at:x.updatedAt||new Date().toISOString()});if(error)throw error;x.syncStatus='synced'}persist();setSync('SYNCED')}catch(e){console.error(e);setSync('SYNC ERROR')}}
function printVisit(v,p){const rows=(v.medicines||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.dose)}</td><td>${esc(x.frequency)}</td><td>${esc(x.duration)}</td></tr>`).join(''),w=window.open('','_blank');if(!w)return alert('ALLOW POP-UPS TO PRINT.');w.document.write(`<!doctype html><html><head><title>Prescription ${esc(p.uhid)}</title><style>@page{size:A5;margin:10mm}body{font-family:Arial;font-size:11px;color:#000}.head{display:flex;justify-content:space-between;border-bottom:1px solid #000;padding-bottom:5px}.row{margin:6px 0}.med{width:100%;border-collapse:collapse}.med th,.med td{border:1px solid #999;padding:4px;text-align:left}.sig{margin-top:45px;text-align:right}</style></head><body><div class="head"><b>PRIME HOSPITAL</b><span>DATE: ${esc(v.date)}</span></div><div class="row"><b>NAME:</b> ${esc(p.firstName)} &nbsp; <b>UHID:</b> ${esc(p.uhid)} &nbsp; <b>AGE/SEX:</b> ${esc(p.age)} / ${esc(p.sex)}</div><div class="row"><b>VITALS:</b> WT ${esc(v.weight)} KG &nbsp; BP ${esc(v.bp)} &nbsp; PULSE ${esc(v.pulse)} &nbsp; SPO2 ${esc(v.spo2)} &nbsp; TEMP ${esc(v.temp)}</div>${[['COMPLAINTS',v.complaints],['KNOWN CASE / HABITS',v.knownCase],['HISTORY',v.history],['EXAMINATION',v.examination],['PD',v.pd]].map(a=>`<div class="row"><b>${a[0]}:</b> ${esc(a[1])}</div>`).join('')}<div class="row"><b>TREATMENT:</b><table class="med"><thead><tr><th>MEDICINE</th><th>DOSE</th><th>FREQUENCY</th><th>DURATION</th></tr></thead><tbody>${rows}</tbody></table></div><div class="row"><b>INVESTIGATION:</b> ${esc(v.investigation)}</div><div class="row"><b>ADVICE:</b> ${esc(v.advice)}</div><div class="row"><b>MANAGEMENT:</b> ${esc(v.management)}</div><div class="sig">DR. ADNAN H. KHAN<br>MBBS • CCDM • ACCD</div><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}
window.addEventListener('online',syncToCloud);window.addEventListener('offline',()=>{$('#net')&&($('#net').textContent='OFFLINE')});boot();